# -*- coding: utf-8 -*-
"""Aplikasi Binary logistic regression with ridge regularization

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k9DGWRJcSGiXVdSoLVC92oqwGudCdG1I

# Aplikasi Binary logistic regression with ridge regularization
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

data = pd.read_csv('ex2data2.txt',header = None)

data.head()

plt.plot(data[0][data[2] == 1],data[1][data[2] == 1],'k+',label = 'Admit')
plt.plot(data[0][data[2] == 0],data[1][data[2] == 0],'yo',label = 'Not Admit')
plt.legend()
plt.show()

log_reg = logistic_regression_reg()
X = data[[0,1]]
y = data[2].values
X1 = log_reg.mapfeature(X,3)

X1.shape

initial_theta = np.zeros((X1.shape[1]))
cost = log_reg.costfunction(initial_theta,X1,y,1)
cost

mincost=log_reg.minimumcost(log_reg.costfunction,initial_theta,X1,y,1)
mincost

ypred = log_reg.predict(X1,mincost)
log_reg.score(y,ypred)

"""# Pengecekan dengan sklearn"""

from sklearn.linear_model import LogisticRegression

linrig = LogisticRegression(C = 1).fit(X1,y)
linrig.score(X1,y)